=======
---
title: "R Notebook"
output:
  html_notebook: default
  pdf_document: default
---
```{r install and load packages}
source("https://bioconductor.org/biocLite.R")

if(!require("pacman", character.only = TRUE)) install.packages("pacman")
pacman::p_load(viper,data.table,dplyr)

```

```{r load fly data}
#load("Fly_Female-tf_regulon.rda")
#saveRDS(regul, file = "Fly_Female-tf_regulon.RDS")

female_regul <- readRDS("Fly_Female-tf_regulon.RDS")

# female_regul_pruned <- pruneRegulon(female, adaptive = TRUE) #EXPERIMENTAL

#load(file = "Fly_Male-tf_regulon.rda")
#saveRDS(regul,"Fly_Male-tf_regulon.RDS")

male_regul <- readRDS("Fly_Male-tf_regulon.RDS")


# load expression assay data

#dsetF <- fread(file ="dgrp.array.exp.female.csv")
#dsetM <- fread(file ="dgrp.array.exp.male.csv")
DGRP_array_males <- readRDS(file = "DGRP_array_males.RDS")
DGRP_array_females <- readRDS(file = "DGRP_array_females.RDS")


# load phenodata

phenocsv <-fread(file = "phenoDelta5.csv")
phenoDelta5 <- readRDS(file = "phenoDelta5.RDS")
```

```{r modify males RNAseq}
rm_list <- fread(file = "rm_list.csv", header = F)
to.remove <- as.data.frame(rm_list)
to.remove <- rm_list$V1
`%ni%` <- Negate(`%in%`)
dsetM2  <- subset(dsetM,select = names(dsetM) %ni% to.remove)
saveRDS(dsetM2, file = "DGRP_array_males.RDS")
```
```{r modify females RNAseq}
rm_list <- fread(file = "rm_list.csv", header = F)
to.remove <- as.data.frame(rm_list)
to.remove <- rm_list$V1
`%ni%` <- Negate(`%in%`)
dsetF2  <- subset(dsetF,select = names(dsetF) %ni% to.remove)
saveRDS(dsetF2, file = "DGRP_array_females.RDS")
```

```{r modify pheno}
library(tibble)
library(dplyr)
pheno <- data.frame(pheno, row.names = 1)
rownames(pheno) <- paste("line", rownames(pheno), sep = "_")

Pheno <- as.data.frame(rownames_to_column(pheno, "Line"))
Pheno <- Pheno[rep(1:nrow(Pheno), each = 2),]
write.csv(Pheno, file = "pheno_5AMPH.csv")

#add replicate column of 1s and 2s to pheno_5AMPH.csv

Pheno <- fread(file = "pheno_5AMPH.csv", drop = "V1")

Pheno <- as.data.table(Pheno)
Pheno[, Line := paste(Line, replicate, sep = ":")]
Pheno[, replicate := NULL]

phenoDelta5 <- data.frame(Pheno, row.names = 1)

saveRDS(phenoDelta5, file = "phenoDelta5.RDS")
```

```{r create metadata, link with pheno}
metadata <- data.frame(labelDescription= "Above average response on night 1",
 row.names= "N1_Delta5")

phenoData5 <- new("AnnotatedDataFrame",
 data=phenoDelta5, varMetadata=metadata)

```

```{r generate male expressionset from matrix}
males.matrix <- as.matrix(DGRP_array_males, rownames = "gene")
#all(rownames(phenoDelta5)==colnames(males.matrix)) #confirm rows and columns match


#males.eset <- ExpressionSet(assayData= males.matrix, phenoData = phenoData5)
```
```{r generate female expressionset from matrix}
females.matrix <- as.matrix(DGRP_array_females, rownames = "gene")
#all(rownames(phenoDelta5)==colnames(females.matrix)) #confirm rows and columns match


#females.eset <- ExpressionSet(assayData= females.matrix, phenoData = phenoData5)
```



```{r prune regulon}
female_pregul <- pruneRegulon(female_regul, 100)
male_pregul <- pruneRegulon(male_regul, 100)
```

```{r create matrices of responders and nonresponders}

truelist <- phenocsv[ which (phenocsv$N1_Delta5 == "TRUE")]
truelist <- as.data.frame(truelist)
truelist <- truelist$V1

falselist <- phenocsv[ which (phenocsv$N1_Delta5 == "FALSE")]
falselist <- as.data.frame(falselist)
falselist <- falselist$V1

# get names/column IDs of Lines in males.matrix considered responders
responders <- subset(males.matrix, select = colnames(males.matrix) %ni% falselist)


# get names/column IDs of Lines in males.matrix considered non-responders
non.responders <- subset(males.matrix, select = colnames(males.matrix) %ni% truelist)
```

```{r AMPH create signature, run msviper}
# create NULL-model and signature with non-responders as the NULL

AMPHvpsig <- viperSignature(responders, non.responders, per=1000)

AMPHmrs <- msviper(AMPHvpsig$signature, male_pregul, AMPHvpsig$nullmodel)

summary(AMPHmrs)

plot(AMPHmrs)
```

```{r MF create signature, run msviper}
# create NULL-model and signature with non-responders as the NULL

MFvpsig <- viperSignature(males.matrix, females.matrix, per=1000)

MFmrs <- msviper(MFvpsig$signature, male_pregul, MFvpsig$nullmodel)

summary(MFmrs)

plot(MFmrs)
```
STOPPING POINT 12/5




```{r}
png(file="heatmap.png", width = 100, height =  100, units = "cm", res = 400)
heatmap(AMPHvpsig$nullmodel)
dev.off()
```



```{r run viper separately}
#females.viper <- viper(females.eset, regulon = female_pregul, method = "scale")

males.viper <- viper(males.eset, regulon = male_pregul, method = "scale") #run viper with ExpressionSet

#dim(males.viper)

tmpsig <- rowTtest(males.viper, "N1_Delta5", "TRUE", "FALSE")
viperTtest <- data.frame(Gene = rownames(tmpsig$p.value), t = round(tmpsig$statistic, 2),
"p-value" = signif(tmpsig$p.value, 3))[order(tmpsig$p.value)[1:10], ]
write.csv(viperTtest, file = "viperTtest.csv")


vpsig <- viperSignature(males.matrix, phenoDelta5, method = "mean", verbose = TRUE) # run viperSignature with 2 matrices, cant specify pheno ref group
vpres <- viper(vpsig, male_regul, verbose = FALSE) #null model
  
#Cannot use ExpressionSet for viperSignature: "Error in (function (classes, fdef, mtable): unable to find an inherited method for function 'pData<-' for signature '"AnnotatedDataFrame", "character"'"
#^^ also applies to numeric and logical

```
```{r} 
 pos <- pData(vpres)[["N1_Delta5"]] %in% c("TRUE")
 d1 <- exprs(males.viper)[, pos]
 colnames(d1) <- pData(males.viper)[["N1_Delta5"]][pos]
 dd <- dist(t(d1), method = "euclidean")
 png(file="malesDelta5_heatmap_euclidean.png",
  width = 100, height =  100, units = "cm", res = 400 )
 heatmap(as.matrix(dd), Rowv = as.dendrogram(hclust(dd, method = "average")), symm = T)
dev.off()
```

```{r msViper}
library(viper)

signature <- rowTtest(males.eset, "N1_Delta5", "TRUE", "FALSE")
nullmodel <- ttestNull(males.eset, "N1_Delta5", "TRUE", "FALSE", per = 1000,
 repos = TRUE, verbose = T) #requires two arguments :(

bstrapsig <-  bootstrapTtest(males.eset, "N1_Delta5", "TRUE", "FALSE", verbose = FALSE)

mrs <- msviper(bstrapsig, male_pregul, nullmodel, verbose = FALSE)
summary(mrs)
mrs <- bootstrapmsviper(mrs, "median")

png(filename = "malesDelta5_msVIPERplot.png")
plot(mrs, cex = .7)
dev.off()


summary(mrs)
```



```{r exploratory clustering}
#females_vipersimilarity <- viperSimilarity(exprs(females.viper))

#need phenodata to look at drug effects!
#png(file="heatmap.png",
#width = 100, height =  100, units = "cm", res = 300 )
#heatmap(as.matrix(as.dist(females_vipersimilarity)), Rowv = as.dendrogram(hclust(as.dist(females_vipersimilarity), method = "average")), symm = T)
#dev.off()

males_vipersimilarity <- viperSimilarity(exprs(males.viper)) # males.viper includes pheno data

png(file="malesDelta5_heatmap_similarity.png",
width = 100, height =  100, units = "cm", res = 300 )
heatmap(as.matrix(as.dist(males_vipersimilarity)), Rowv = as.dendrogram(hclust(as.dist(males_vipersimilarity), method = "average")), symm = T) 
dev.off()

```
>>>>>>> master
